#!/bin/bash

if [ -z "$1" ]
then
  start=40800000
else
  start="$1"
fi

if [ -z "$2" ]
then
  end=$(($start + 9999))
else
  end="$2"
fi

FIND="iPhn6"
OUT=`echo "$FIND" | sed 's/ /_/g'`

for i in `seq -f '%.0f' "$start" "$end"`
do
  echo -n "$i... "
  out=`wget -O - -q "https://www.optusbusiness.com.au/test_track_status.php?orderno=$i&request_json=true&jsoncallback=jQuery16202045904896222055_1411536091719&_=1411536118502&site=consumer"`
  echo "$out" | grep "$FIND" 2>&1 > /dev/null
  if [ $? -eq 0 ]
  then
    echo "$out" | sed -e 's/^.*({/{/' -e 's/}).*$/}/g' >> ./"$OUT"
    echo "Found at {$i}"
  fi
done
